from pathlib import Path
from zipfile import ZipFile, ZIP_DEFLATED
from xml.sax.saxutils import escape

OUT = 'pelican-bay-ride-slideshow.pptx'
EMU = 914400

def e(n): return str(round(n * EMU))

def shape(i, name, x, y, w, h, fill='none', text=None, color='173A43', size=1800, bold=False, rounded=False):
    geom = 'roundRect' if rounded else 'rect'
    fill_xml = '<a:noFill/>' if fill == 'none' else f'<a:solidFill><a:srgbClr val="{fill}"/></a:solidFill>'
    sppr = f'<p:spPr><a:xfrm><a:off x="{e(x)}" y="{e(y)}"/><a:ext cx="{e(w)}" cy="{e(h)}"/></a:xfrm><a:prstGeom prst="{geom}"><a:avLst/></a:prstGeom>{fill_xml}<a:ln><a:noFill/></a:ln></p:spPr>'
    tx = ''
    if text:
        runs = ''.join(f'<a:r><a:rPr lang="en-US" sz="{size}" b="{1 if bold else 0}"><a:solidFill><a:srgbClr val="{color}"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t>{escape(line)}</a:t></a:r>' if j == 0 else f'<a:br><a:rPr lang="en-US" sz="{size}"/></a:br><a:r><a:rPr lang="en-US" sz="{size}" b="{1 if bold else 0}"><a:solidFill><a:srgbClr val="{color}"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t>{escape(line)}</a:t></a:r>' for j,line in enumerate(text.split('\n')))
        tx = f'<p:txBody><a:bodyPr wrap="square" lIns="0" tIns="0" rIns="0" bIns="0" anchor="ctr"/><a:lstStyle/><a:p><a:pPr algn="l"/>{runs}<a:endParaRPr lang="en-US" sz="{size}"/></a:p></p:txBody>'
    return f'<p:sp><p:nvSpPr><p:cNvPr id="{i}" name="{escape(name)}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>{sppr}{tx}</p:sp>'

def pic(i, x, y, w, h):
    return f'<p:pic><p:nvPicPr><p:cNvPr id="{i}" name="Pelican illustration"/><p:cNvPicPr><a:picLocks noChangeAspect="1"/></p:cNvPicPr><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="rId2"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="{e(x)}" y="{e(y)}"/><a:ext cx="{e(w)}" cy="{e(h)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic>'

def slide(items):
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="F7FBF7"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>{''.join(items)}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>'''

slides = [
    slide([shape(2,'Accent',.72,.8,.12,1.35,'F1A936'), shape(3,'Kicker',1.02,.88,5,.35,text='A DAY AROUND THE BAY',color='D77836',size=1150,bold=True), shape(4,'Title',1,1.35,5.35,1.6,text='The Bay Ride\nStarts Here',size=3300,bold=True), shape(5,'Subtitle',1.03,3.13,4.9,.7,text='A slow ride, salty air, and new places to explore.',color='477078',size=1700), shape(6,'Tag',1.03,4.22,2.2,.52,'173A43','A SAMPLE STORY',color='FFFFFF',size=1050,bold=True,rounded=True), pic(7,6,.65,6.55,4.5), shape(8,'Footer',1.03,6.8,4,.28,text='01   /   THE JOURNEY',color='6D8B87',size=1000,bold=True)]),
    slide([shape(2,'Eyebrow',.78,.62,4,.32,text='THE ROUTE',color='D77836',size=1100,bold=True), shape(3,'Headline',.78,1.04,5,1.15,text='Follow the\nshoreline.',size=2900,bold=True), shape(4,'Body',.8,2.55,4.6,1.1,text='A winding waterfront path turns a simple bike ride into a full day out.',color='477078',size=1700), shape(5,'Start card',.8,4.28,2.45,1.3,'E2F1E8',rounded=True), shape(6,'Pause card',3.48,4.28,2.45,1.3,'FFF0CF',rounded=True), shape(7,'Start text',1.02,4.5,2,.8,text='01  /  Start\nRoll out from the old harbor.',color='24535B',size=1200,bold=True), shape(8,'Pause text',3.7,4.5,2,.8,text='02  /  Pause\nSnack by the water.',color='24535B',size=1200,bold=True), pic(9,6.25,1.45,6.1,4.15), shape(10,'Footer',.8,6.8,4,.28,text='02   /   THE ROUTE',color='6D8B87',size=1000,bold=True)]),
    slide([shape(2,'Eyebrow',.78,.62,4,.32,text='THE LITTLE MOMENTS',color='D77836',size=1100,bold=True), shape(3,'Headline',.78,1.02,5.2,.7,text='Make room to wander',size=2700,bold=True), shape(4,'Lead',.8,1.9,4.65,.75,text='Sea views, a roadside flower, and an unhurried pace make the ride memorable.',color='477078',size=1600), shape(5,'Teal swatch',.8,3.24,1.45,1.15,'388B9C',rounded=True), shape(6,'Green swatch',2.48,3.24,1.45,1.15,'C7E9C4',rounded=True), shape(7,'Yellow swatch',4.16,3.24,1.45,1.15,'F1A936',rounded=True), shape(8,'Labels',.8,4.55,5,.7,text='SEA AIR      GREEN WAY      GOLDEN HOUR',color='24535B',size=1200,bold=True), pic(9,6.35,1.45,6.05,4.1), shape(10,'Closing line',.8,5.65,5.2,.5,text='The best part is taking the long way home.',color='D77836',size=1700,bold=True), shape(11,'Footer',.8,6.8,4,.28,text='03   /   THE GOOD PART',color='6D8B87',size=1000,bold=True)])
]

def rels(s): return f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">{s}</Relationships>'

content_types = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="svg" ContentType="image/svg+xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/>' + ''.join(f'<Override PartName="/ppt/slides/slide{i}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>' for i in range(1,4)) + '</Types>'

with ZipFile(OUT,'w',ZIP_DEFLATED) as z:
    z.writestr('[Content_Types].xml',content_types)
    z.writestr('_rels/.rels',rels('<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>'))
    z.writestr('ppt/presentation.xml','''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst><p:sldId id="256" r:id="rId2"/><p:sldId id="257" r:id="rId3"/><p:sldId id="258" r:id="rId4"/></p:sldIdLst><p:sldSz cx="12191995" cy="6858000" type="wide"/><p:notesSz cx="6858000" cy="9144000"/><p:defaultTextStyle/></p:presentation>''')
    z.writestr('ppt/_rels/presentation.xml.rels',rels('<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide2.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide3.xml"/>'))
    master = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0"" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="388B9C" accent2="F1A936" accent3="C7E9C4" accent4="E8755D" accent5="477078" accent6="DFF5F2" hlink="0000FF" folHlink="800080"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>'''.replace('x="0"" y=', 'x="0" y=')
    z.writestr('ppt/slideMasters/slideMaster1.xml',master)
    z.writestr('ppt/slideMasters/_rels/slideMaster1.xml.rels',rels('<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/>'))
    z.writestr('ppt/slideLayouts/slideLayout1.xml','''<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>''')
    z.writestr('ppt/slideLayouts/_rels/slideLayout1.xml.rels',rels('<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/>'))
    for i,s in enumerate(slides,1):
        z.writestr(f'ppt/slides/slide{i}.xml',s)
        z.writestr(f'ppt/slides/_rels/slide{i}.xml.rels',rels('<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="../media/pelican.svg"/>'))
    z.write('pelican-on-a-bike.svg','ppt/media/pelican.svg')
print(OUT)
